import { ServiceCenter } from '../types';
import { BRANDS_DATASET, CARS_DATASET } from '../data/carsDataset';

export const MOCK_BRANDS = BRANDS_DATASET;
export const MOCK_VEHICLES = CARS_DATASET;

export const MOCK_SERVICE_CENTERS: ServiceCenter[] = [
  {
    id: 'sc-mum-01',
    name: 'Tata Motors Service Hub — Worli',
    brand: 'Tata Motors',
    address: 'Plot 14, Dr. Annie Besant Rd, Worli',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400018',
    latitude: 19.0178,
    longitude: 72.8185,
    phone: '+91 22 6655 4321',
    email: 'worli.service@tatamotors.com',
    opening_hours: '08:30 AM - 07:00 PM (Mon-Sat)',
    rating: 4.7,
    services: ['Periodic Maintenance', 'EV Charging & Battery Health', 'Body Shop & Paint', 'Express 60-Min Service'],
    distance_km: 3.2,
  },
  {
    id: 'sc-mum-02',
    name: 'Maruti Suzuki Arena Service — Andheri East',
    brand: 'Maruti Suzuki',
    address: 'MIDC Central Rd, Chakala, Andheri East',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400093',
    latitude: 19.1172,
    longitude: 72.8687,
    phone: '+91 22 2838 9012',
    email: 'service.andheri@marutisuzuki.com',
    opening_hours: '09:00 AM - 08:00 PM (All Days)',
    rating: 4.6,
    services: ['General Service', 'CNG Kit Inspection', 'Wheel Alignment', 'Insurance Claim Assistance'],
    distance_km: 5.8,
  },
  {
    id: 'sc-blr-01',
    name: 'Hyundai Motor Plaza — Koramangala',
    brand: 'Hyundai',
    address: '100 Feet Rd, 4th Block, Koramangala',
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560034',
    latitude: 12.9352,
    longitude: 77.6245,
    phone: '+91 80 4123 7890',
    email: 'koramangala@hyundai-plaza.com',
    opening_hours: '08:30 AM - 06:30 PM (Mon-Sat)',
    rating: 4.8,
    services: ['Connected Car Diagnostics', 'Scheduled Maintenance', 'Ceramic Coating', 'Tyre Care'],
    distance_km: 4.1,
  },
  {
    id: 'sc-del-01',
    name: 'Mahindra Service Zone — Connaught Place',
    brand: 'Mahindra',
    address: 'Barakhamba Road, Connaught Place',
    city: 'New Delhi',
    state: 'Delhi',
    pincode: '110001',
    latitude: 28.6289,
    longitude: 77.2219,
    phone: '+91 11 2341 5678',
    email: 'cp.service@mahindra.com',
    opening_hours: '09:00 AM - 07:00 PM (Mon-Sat)',
    rating: 4.7,
    services: ['4x4 Drivetrain Service', 'Suspension Overhaul', 'Software Updates', 'AC Diagnostics'],
    distance_km: 2.9,
  },
  {
    id: 'sc-hyd-01',
    name: 'Toyota Nippon Motor Hub — Hitec City',
    brand: 'Toyota',
    address: 'Madhapur Main Rd, Hitec City',
    city: 'Hyderabad',
    state: 'Telangana',
    pincode: '500081',
    latitude: 17.4483,
    longitude: 78.3915,
    phone: '+91 40 2311 8899',
    email: 'service.hyd@toyotanippon.com',
    opening_hours: '08:30 AM - 07:30 PM (All Days)',
    rating: 4.9,
    services: ['Express Maintenance (60 min)', 'Engine Overhaul', 'Hybrid Battery Health', 'Quick Detailing'],
    distance_km: 3.8,
  },
];
